### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by OliverSpeak** [spekulatius/PHPScraper#116]
I am not sure if I'm simply missing something, but after installing phpscraper and simply writing this:
`<?php
require 'vendor/autoload.php';
$web = new \spekulatius\phpscraper;
?>`
Brings this error.
`Fatal error: Default value for parameters with a class type can only be NULL in .../vendor/symfony/browser-kit/AbstractBrowser.php on line 136`
I'm using vanilla php with XAMPP.

**Comment by spekulatius** [comment]
Hey @OliverSpeak 

can you share the whole error stack?

Cheers,
Peter

**Comment by spekulatius** [comment]
Closing this for now.
