### ISSUE TITLE
Scraping using classes

### ISSUE THREAD

**Issue by eborguezao** [spekulatius/PHPScraper#12]
Is there data scraping using classes as a reference, or DOM structure? Thank you.

**Comment by spekulatius** [comment]
Just to confirm what you are trying to do: you would like to parse data from a page using CSS classes (or alternatively DOM selectors)?

**Comment by spekulatius** [comment]
Hey @eborguezao 

I'll close this for now. If you want you can reopen it.

Cheers,
Peter
