### ISSUE TITLE
Versioning and Changelog

### ISSUE THREAD

**Issue by nadar** [spekulatius/PHPScraper#138]
Hi

Its a great project, we use that library, its great :+1: thanks for all the work!

We are not sure what the versioning concept of this library looks like, also we could not find information about what has changed (a changelog), there are only tags: https://github.com/spekulatius/PHPScraper/tags. So it would be nice to read something about what is the versioning strategy and when are breaks expected.

Of course [semver](https://semver.org/) would be nice with an 1.0.0 release and a CHANGELOG.md and UPGRADE.md. My personal example would look like this https://github.com/nadar/quill-delta-parser/blob/master/CHANGELOG.md and this https://github.com/nadar/quill-delta-parser/blob/master/UPGRADE.md

Thanks and keep up to great work!

**Comment by spekulatius** [comment]
Hey @nadar,

thank you for your message. Great to hear it's useful for you!

I can see that the development process isn't overly clear atm. The main principle -so far- has been *release early, release often*.

The lib should follow semver, unless I missed something. I'll add a changelog and upgrade instructions with the next general update of the readme. Good idea :+1: It should come soon(ish).

Feel free to share any other feedback or ideas you might have :)

Cheers,
Peter

**Comment by nadar** [comment]
Should i send a PR with those files? Is there a reason for starting versioning with 0? I would recommend a 1.0 release:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

https://semver.org/#spec-item-4

**Comment by spekulatius** [comment]
> Should i send a PR with those files? 

All good, it needs to be build up with actual information. 

> Is there a reason for starting versioning with 0?

0.x is correct - while usable it's still in (heavy) development. I'm avoiding breaking changes as good as possible to allow early adopters to use it. 1.0 comes once the feature set is completed (subjective).

**Comment by nadar** [comment]
All right, i understand. So there would be nice to see a roadmap of what is missing :smile: 

[2 1/2 years of development](https://github.com/spekulatius/PHPScraper/releases/tag/0.1)  and [16k downlods](https://packagist.org/packages/spekulatius/phpscraper/stats). I would consider this as a fearue rich, first stable release :-)

**Comment by spekulatius** [comment]
Yeah, it's been a while :D I didn't even notice it's 16k downloads already. That's quite a bit more than I expected :star_struck: 

I'm on the push to 1.0 :muscle: I'll make sure to get the roadmap and docs updated before :+1:

**Comment by spekulatius** [comment]
Hey @nadar 

I've added a CHANGELOG.md and UPGRADING.md (still empty). Feel free to let me know if you have any feedback :)

Cheers,
Peter

**Comment by nadar** [comment]
Today we recieved an update, but could not find something in changelog or releases (it seems to be a tag 1.0.1)

![image](https://user-images.githubusercontent.com/3417221/205237497-2a918594-835c-4ab0-af58-be003f233fe6.png)

**Comment by spekulatius** [comment]
Hey @nadar,

Thanks for the reminder. I've added it in. Let me know if any questions come up.

Cheers,
Peter
