### ISSUE TITLE
[Proposal] Exposing Goutte/Client via client() property/callable method

### ISSUE THREAD

**Issue by amurrell** [spekulatius/PHPScraper#154]
Previously, [there was an issue](https://github.com/spekulatius/PHPScraper/issues/60) about exposing the Goutte/Client via core that was fixed but never released.

My code was depending on it via a dev branch.

In the latest version, this functionality was removed. I recommend that it be added back in.

In `UsesGoutte.php`,

```PHP
/**
 * Retrieve the client
 *
 * @param \Goutte\Client $client
 */
public function client(): GoutteClient
{
    return $this->client;
}
```

**Comment by spekulatius** [comment]
Merged, thank you @amurrell!
