### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by alanx15a2** [spekulatius/PHPScraper#159]
When i run the sample code:
```php
$web = new \Spekulatius\PHPScraper\PHPScraper();
$web->go('https://www.google.com/');
echo $web->title;
```
It return:
```
Spekulatius\PHPScraper\Core::setHttpClient(): Argument #1 ($httpClient) must be of type Symfony\Component\HttpClient\CurlHttpClient, Symfony\Component\HttpClient\NativeHttpClient given, called in C:\www\web-crawer\vendor\spekulatius\phpscraper\src\PHPScraper.php on line 108
```
### Environments
PHP: 8.1.13
PHPScraper: 1.0.1

**Comment by spekulatius** [comment]
Ah, I see you want to inject another type of HttpClient?

**Comment by alanx15a2** [comment]
Yeah, we use ```SymfonyHttpClient::create()``` to create the core.
The ```create()``` method will return many type of HttpClient, and all of them are implements of HttpClientInterface.
So I think we should inject HttpClientInterface here.

**Comment by spekulatius** [comment]
Yeah, sounds good. I'll merge it in.
