### ISSUE TITLE
What location PHPSCrapper based on?

### ISSUE THREAD

**Issue by datlechin** [spekulatius/PHPScraper#175]
Hi @spekulatius,

Some user using my https://github.com/datlechin/flarum-link-preview that used PHPScrapper,
They see the scrap content is in other language, is the website content based on where the website is hosted?

![image](https://user-images.githubusercontent.com/56961917/208363577-519f0a1b-6775-49ec-a2ea-3a64d921991f.png)

https://discuss.flarum.org/d/30011-link-preview/178

**Comment by spekulatius** [comment]
Hello @datlechin 

I haven't explicitly set any locale. Can you check with a site like [this](https://manytools.org/http-html-text/http-request-headers/) what headers are sent?

Cheers,
Peter
