### ISSUE TITLE
Syntax Error when i tried using PHP 7.3

### ISSUE THREAD

**Issue by ryanjauhari** [spekulatius/PHPScraper#180]
PHP thrown and error like this 
```
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /www/wwwroot/mydomain.com/dist/tools_box/vendor/spekulatius/phpscraper/src/UsesFileParsers.php on line 24
```

**Comment by spekulatius** [comment]
Hello @ryanjauhari

oh, okay. Sounds like 7.3 (and 7.4) should go out anyways: https://www.php.net/supported-versions.php I'll get it on the way.

Cheers,
Peter

**Comment by spekulatius** [comment]
The fix is merged into master and will be released soon as v2. Feel free to test the current master to see if everything works for you @ryanjauhari

**Comment by spekulatius** [comment]
Hey @ryanjauhari 

I've tagged a new release that should cover this issue.

Cheers,
Peter
