### ISSUE TITLE
fabpot/goutte

### ISSUE THREAD

**Issue by nadar** [spekulatius/PHPScraper#181]
it seems that one of your deps is abandoned, maybe consider using the suggested replacement? Or is there a specific reason?

> Package fabpot/goutte is abandoned, you should avoid using it. Use symfony/browser-kit instead.

**Comment by spekulatius** [comment]
Hey @nadar 

yeah, Goutte is more or less just a wrapper around other packages at this point. It looks as if using the original dependencies instead is the way to go. I'm pretty busy atm. Do you think you could look into this? Otherwise it will have to wait a bit.

Cheers,
Peter

**Comment by monsefsolutions** [comment]
First of all, thank you @spekulatius for this great scraper and all the work you put into it. I really appreciate it. 

I get a similar error like @nadar mentioned when switching to PHP 8.2.6.  

`The "Goutte\Client" class is deprecated, use "Symfony\Component\BrowserKit\HttpBrowser" instead`

I wish I could help with solving the error, but unfortunately, I'm not that familiar with Goutte and BrowserKit. I will wait patiently for the fix and in the meantime switch back to PHP 7.4.x. Again, thanks for this amazing tool.

**Comment by spekulatius** [comment]
Hello @nadar and @monsefsolutions,

I've pushed a branch called `181-switch-from-goutte-to-browser-kit` to address this issue by switching the base lib. Could you clone the repo into your vendor folder and test this? Thank you!

Cheers,
Peter

**Comment by nadar** [comment]
In order to test branches, packagist automatically publishes branches. you can access them by using `dev-<branch-name>`. So in order to test i just did `"spekulatius/phpscraper": "dev-181-switch-from-goutte-to-browser-kit as 1.0.2"` and `composer u`.

Looks good so far, will make some tests. thanks

**Comment by spekulatius** [comment]
I've merged the branch and will tag a new major release once a number of smaller fixes have been included @nadar & @monsefsolutions.

**Comment by nadar** [comment]
@spekulatius great, thanks for taking care :+1:

**Comment by spekulatius** [comment]
Hello @nadar & @monsefsolutions 

I've pushed the last changes for v2. Could you give the `v2` branch a spin and see if you notice any problems before I merge and tag it? Thank you in advance!

Peter

**Comment by monsefsolutions** [comment]
Hi Peter,

Thank you again for the effort! I will test it at the end of this week and
let you know.

Indien u nog vragen en/of opmerkingen heeft naar aanleiding van dit
bericht, vraag ik u vriendelijk contact met me op te nemen.

Met vriendelijke groet,
*Arash Monsef*



*Monsef Solutions *| Denken in oplossingen
monsef-solutions.nl <https://www.monsef-solutions.nl> |
***@***.*** | 06 533 12 558 <0653312558>

Kamer van Koophandel: 73930865 | Btw: NL220133384B01

Dit bericht is vertrouwelijk en enkel bestemd voor de bedoelde
geadresseerde(n). Indien u niet de bedoelde ontvanger bent, wordt u
verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen
direct te verwijderen en/of te vernietigen. Het is verboden deze mail en
eventuele bijlagen te vermenigvuldigen, te openbaren, door te sturen, op te
slaan of op elke andere wijze te gebruiken voor welk doeleinde dan ook.
Monsef Solutions accepteert geen enkele verantwoordelijkheid of
aansprakelijkheid voor welke schade dan ook die voortvloeit uit de inhoud
van dit bericht.


Op di 6 jun 2023 om 07:57 schreef Peter Thaleikis ***@***.***

**Comment by spekulatius** [comment]
Okay, let me know if you find any issues @monsefsolutions :+1:

**Comment by spekulatius** [comment]
Hello @monsefsolutions and @nadar,

I've tagged a new major release. Feel free to give it a try and let me know if you find any issues.

Cheers,
Peter

**Comment by nadar** [comment]
Thanks! I just upgraded and tested to 2.0, works :+1:
