### ISSUE TITLE
psr/http-message 2.0 compatibility

### ISSUE THREAD

**Issue by aphoe** [spekulatius/PHPScraper#197]
I could not install the package on Laravel 10.23 or Laravel 9.5 without using the  `--with-all-dependencies` option.

And on using the option, it downgraded the `psr/http-message` from 2.0 to 1.1

**Comment by spekulatius** [comment]
Hello @aphoe,

I've had a look and noticed that `psr/http-message` is locked at 1.1 due to `league/uri` being locked at 6.8:

```bash
09:39 $ composer update "psr/http-message:2" --dry-run
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - league/uri is locked to version 6.8.0 and an update of this package was not requested.
    - league/uri 6.8.0 requires psr/http-message ^1.0.1 -> found psr/http-message[1.0.1, 1.1] but it conflicts with your temporary update constraint (psr/http-message:2).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

Do you think you could check what is needed to get the next version of uri going?

Cheers,
Peter

**Comment by spekulatius** [comment]
Hello @aphoe,

with the current version the problem should be resolved. I'll close this issue for now.

Cheers,
Peter
