### ISSUE TITLE
upgrade path for 3.0

### ISSUE THREAD

**Issue by nadar** [spekulatius/PHPScraper#205]
hi, i saw  there is a 3.0 release, is there an upgrade path available? Or what to expect when change to next major version? i could not find anything in: https://github.com/spekulatius/PHPScraper/blob/master/UPGRADING.md

**Comment by nadar** [comment]
@spekulatius sorry for asking again. not sure what is expected with the new tagged 3.0 version?

**Comment by spekulatius** [comment]
Hey @nadar,

v3 was already released on April, 9th: https://github.com/spekulatius/PHPScraper/tags

As far as I remember the changes there shouldn't be any changes required.

The only part missing was a release note on GitHub repo. I've just caught up on this on - sorry for the delay.

Cheers,
Peter

**Comment by nadar** [comment]
dear @spekulatius ok, so its safe to upgrade. because a major release (2.x to 3.x) usual means that my code could break when update. so this is not the case then. thanks

**Comment by spekulatius** [comment]
Feel free to look over the diff to ensure it is compatible with your code

**Comment by spekulatius** [comment]
https://github.com/spekulatius/PHPScraper/compare/2.0.0...3.0.0
