### ISSUE TITLE
Doesn't recognize the correct PHP version ...

### ISSUE THREAD

**Issue by Mela** [spekulatius/PHPScraper#208]
Hi,

when installing PHP Scraper with composer, I'm getting the following error: 

`Cannot use spekulatius/phpscraper's latest version 3.0.0 as it requires php ^8.1 which is not satisfied by your platform.`

Installed is PHP 8.3.  

Any ideas, how to fix this?

Regards,

Mela

**Comment by Mela** [comment]
Okay, fixed it by `/usr/bin/php83 /usr/bin/composer update.
`
Sorry.

**Comment by spekulatius** [comment]
Hey @Mela 

all good, sometimes the /usr/bin/php isn't set to the latest available one.

Peter
