### ISSUE TITLE
 links from div

### ISSUE THREAD

**Issue by zigou13** [spekulatius/PHPScraper#30]
Hello, I have a problem, I want to have all the links from // * [@ id = "content"] 'how do I do?

**Comment by spekulatius** [comment]
Hey @zigou13,

have you  tried using `$scraper->filter('//*[@id="content"]')`?

Cheers,
Peter

**Comment by zigou13** [comment]
Yes it works but after I can not get the a href out of the id ="content"

`public function content()
    {
		
		$content = $this->filterExtractAttributes('//*[@id="content"]', ['_name', '_text','_href','_alt']);
		return $content;`
}

$content = $web->content;


Allemagne (43)
--
  |  
  | Angleterre (79)
  |  
  | Autriche (8)
  |  
  | Belgique (19)
  |  
  | Biélorussie (1)

**Comment by zigou13** [comment]
It's good
`$content = $this->filterExtractAttributes('//*[@id="content"] //a', ['_name', '_text','href','alt']);`

`[3] => Array
        (
            [0] => a
            [1] => Allemagne
            [2] => /my-link
            [3] => 
        )`

**Comment by spekulatius** [comment]
Ah, I see, you are pre-selecting the element using the `div` and the want the `a`-tags below. Everything is sorted now? :)

**Comment by zigou13** [comment]
yes thank you, I continue my parsing

**Comment by spekulatius** [comment]
Awesome, great it's useful!

I'll close this for now. Feel free to open a new one or reply if anything else comes up :+1:
