### ISSUE TITLE
PHPScraper + Timeout 

### ISSUE THREAD

**Issue by Benjouke** [spekulatius/PHPScraper#43]
Hello,

How to make a condition if the timeout exceeds a certain number of seconds?

Thank

**Comment by spekulatius** [comment]
Hey @Benjouke 

I haven't looked into timeout issue as it didn't happen for me really. I'll check it out and see how it could be enabled/documented better.

Peter

**Comment by tonybyng** [comment]
@spekulatius I think you can specify a timeout option with an options parameter when you create a Goutte client, so if you allow an optional options parameter to be passed in on the constructor it would give most flexibility as other parameters could be passed through as well?  The Goutte readme passes through a new HttpClient object with a timeout option when calling the Goutte client constructor https://github.com/FriendsOfPHP/Goutte

**Comment by spekulatius** [comment]
Hey @tonybyng and @Benjouke,

better late than never :rofl: I've added support to configure timeout directly.

Cheers,
Peter
