### ISSUE TITLE
Make public function to access Client (Goutte)

### ISSUE THREAD

**Issue by amurrell** [spekulatius/PHPScraper#60]
I wanted to know the response code of the url but could not get access.

Looking at [Goutte under the hood](https://github.com/FriendsOfPHP/Goutte/issues/249#issuecomment-581638444), I think I could get it if I could do something like:

```
$web->getClient()->getInternalResponse()->getStatusCode()
```

So, I would like a function to get access to the $client, like:

```
public function getClient()
{
   return $this->client;
}
```

**Comment by spekulatius** [comment]
Hello @amurrell,

How about exposing the response code directly? This would allow to check easily if the navigation was successful...

Cheers,
Peter

**Comment by amurrell** [comment]
Access to the client is really desired - I also need to be able to set the user agent:

In Goutte, you can:

```
$client->setServerParameter('HTTP_USER_AGENT', 'user agent');
```

**Comment by spekulatius** [comment]
Hey @amurrell,

I've added a method to expose the client. You should be able to call it now. Can you check if this works for you?

Cheers,
Peter
