### ISSUE TITLE
composer update

### ISSUE THREAD

**Issue by datlechin** [spekulatius/PHPScraper#64]
`spekulatius/phpscraper 0.5.2 requires symfony/dom-crawler ^5.0 -> found symfony/dom-crawler[v5.0.0, ..., v5.4.3] but the package is fixed to v6.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.`

**Comment by spekulatius** [comment]
Hello @datlechin,

PHP scraper is using the DOM crawler package v5 atm. Before v6 can be used some stuff needs to be tweaked. I haven't had time to complete it yet. I'll ping you once it's completed and can be tested.

Cheers,
Peter
