### ISSUE TITLE
deprecate magic properties / methods

### ISSUE THREAD

**Issue by tacman** [spekulatius/PHPScraper#82]
In my branch I've removed the magic __get and __call methods, and moved what was core into the phpscraper, so now there is only one class.

After a while I got tired of find/replace, so I created a rector rule to change the properties to method.

Is there a demo repository that uses I can use to test my branch?  Tests are passing, except for the ones related to internal/external links, which I'll address in another issue.

**Comment by spekulatius** [comment]
Hey @tacman,

I like the magic properties. The simplicity of PHPscraper is part of the reason I've written it.

Cheers,
Peter

**Comment by tacman** [comment]
Hmm.  I think one class is easier than 2, and magic methods can't be statically checked or linked with PhpStorm.  And with a rector rule, it's easy to update, so in my mind it's no less simple without the magic methods.  just my 2 cents.

**Comment by spekulatius** [comment]
Yeah, it's kind a personal opinion thing I guess.
